server:
  port: 88
  # undertow配置
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
  servlet:
    context-path: /edu

spring:
  profiles:
    active: dev
  # thymeleaf相关配置
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  # json相关配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
# actuator配置
management:
  endpoints:
    web:
      #默认是/actuator
      base-path: /list
      exposure:
        #暴露监控访问接口，默认是/health和/info
        include:
          - info
          - health
        #显式屏蔽监控访问接口
        exclude:
          - self
        #  - metrics
  #开放关闭应用程序端点，不建议开启
  endpoint:
    shutdown:
      enabled: false